MyLove/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :reports
  resources :report_types
  resources :messages
  resources :message_types
  resources :rols
  resources :contacts

  root 'reports#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

MyLove/app/models/rol.rb
class Rol < ApplicationRecord
end

MyLove/app/controllers/rols_controller.rb
class RolsController < ApplicationController
  before_action :set_rol, only: [:show, :edit, :update, :destroy]

  # GET /rols
  # GET /rols.json
  def index
    @rols = Rol.all
  end

  # GET /rols/1
  # GET /rols/1.json
  def show
  end

  # GET /rols/new
  def new
    @rol = Rol.new
  end

  # GET /rols/1/edit
  def edit
  end

  # POST /rols
  # POST /rols.json
  def create
    @rol = Rol.new(rol_params)

    respond_to do |format|
      if @rol.save
        format.html { redirect_to @rol, notice: 'Rol was successfully created.' }
        format.json { render :show, status: :created, location: @rol }
      else
        format.html { render :new }
        format.json { render json: @rol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rols/1
  # PATCH/PUT /rols/1.json
  def update
    respond_to do |format|
      if @rol.update(rol_params)
        format.html { redirect_to @rol, notice: 'Rol was successfully updated.' }
        format.json { render :show, status: :ok, location: @rol }
      else
        format.html { render :edit }
        format.json { render json: @rol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rols/1
  # DELETE /rols/1.json
  def destroy
    @rol.destroy
    respond_to do |format|
      format.html { redirect_to rols_url, notice: 'Rol was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rol
      @rol = Rol.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rol_params
      params.require(:rol).permit(:NameRol)
    end
end

MyLove/app/helpers/rols_helper.rb
module RolsHelper
end

MyLove/app/views/rols/_form.html.erb
<%= form_for(rol) do |f| %>
  <% if rol.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rol.errors.count, "error") %> prohibited this rol from being saved:</h2>

      <ul>
      <% rol.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :NameRol %>
    <%= f.text_field :NameRol %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MyLove/app/views/rols/edit.html.erb
<h1>Editing Rol</h1>

<%= render 'form', rol: @rol %>

<%= link_to 'Show', @rol %> |
<%= link_to 'Back', rols_path %>

MyLove/app/views/rols/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rols</h1>

<table>
  <thead>
    <tr>
      <th>Namerol</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rols.each do |rol| %>
      <tr>
        <td><%= rol.NameRol %></td>
        <td><%= link_to 'Show', rol %></td>
        <td><%= link_to 'Edit', edit_rol_path(rol) %></td>
        <td><%= link_to 'Destroy', rol, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rol', new_rol_path %>

MyLove/app/views/rols/new.html.erb
<h1>New Rol</h1>

<%= render 'form', rol: @rol %>

<%= link_to 'Back', rols_path %>

MyLove/app/views/rols/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Namerol:</strong>
  <%= @rol.NameRol %>
</p>

<%= link_to 'Edit', edit_rol_path(@rol) %> |
<%= link_to 'Back', rols_path %>