MyLove/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :reports
  resources :report_types
  resources :messages
  resources :message_types
  resources :rols
  resources :contacts

  root 'reports#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

MyLove/app/controllers/message_types_controller.rb
class MessageTypesController < ApplicationController
  before_action :set_message_type, only: [:show, :edit, :update, :destroy]

  # GET /message_types
  # GET /message_types.json
  def index
    @message_types = MessageType.all
  end

  # GET /message_types/1
  # GET /message_types/1.json
  def show
  end

  # GET /message_types/new
  def new
    @message_type = MessageType.new
  end

  # GET /message_types/1/edit
  def edit
  end

  # POST /message_types
  # POST /message_types.json
  def create
    @message_type = MessageType.new(message_type_params)

    respond_to do |format|
      if @message_type.save
        format.html { redirect_to @message_type, notice: 'Message type was successfully created.' }
        format.json { render :show, status: :created, location: @message_type }
      else
        format.html { render :new }
        format.json { render json: @message_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /message_types/1
  # PATCH/PUT /message_types/1.json
  def update
    respond_to do |format|
      if @message_type.update(message_type_params)
        format.html { redirect_to @message_type, notice: 'Message type was successfully updated.' }
        format.json { render :show, status: :ok, location: @message_type }
      else
        format.html { render :edit }
        format.json { render json: @message_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /message_types/1
  # DELETE /message_types/1.json
  def destroy
    @message_type.destroy
    respond_to do |format|
      format.html { redirect_to message_types_url, notice: 'Message type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message_type
      @message_type = MessageType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_type_params
      params.require(:message_type).permit(:NameMessage)
    end
end

MyLove/app/helpers/message_types_helper.rb
module MessageTypesHelper
end

MyLove/app/views/message_types/_form.html.erb
<%= form_for(message_type) do |f| %>
  <% if message_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message_type.errors.count, "error") %> prohibited this message_type from being saved:</h2>

      <ul>
      <% message_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :NameMessage %>
    <%= f.text_field :NameMessage %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MyLove/app/views/message_types/edit.html.erb
<h1>Editing Message Type</h1>

<%= render 'form', message_type: @message_type %>

<%= link_to 'Show', @message_type %> |
<%= link_to 'Back', message_types_path %>

MyLove/app/views/message_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Message Types</h1>

<table>
  <thead>
    <tr>
      <th>Namemessage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @message_types.each do |message_type| %>
      <tr>
        <td><%= message_type.NameMessage %></td>
        <td><%= link_to 'Show', message_type %></td>
        <td><%= link_to 'Edit', edit_message_type_path(message_type) %></td>
        <td><%= link_to 'Destroy', message_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message Type', new_message_type_path %>

MyLove/app/views/message_types/new.html.erb
<h1>New Message Type</h1>

<%= render 'form', message_type: @message_type %>

<%= link_to 'Back', message_types_path %>

MyLove/app/views/message_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Namemessage:</strong>
  <%= @message_type.NameMessage %>
</p>

<%= link_to 'Edit', edit_message_type_path(@message_type) %> |
<%= link_to 'Back', message_types_path %>